
version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=host.docker.internal
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    networks:
      - app-tier  
  
  app:
    container_name: encurtadordelink
    build: .  
    command: npm start
    networks:
      - app-tier
    env_file:
      - .env
    ports:
      - "3333:3333"
    
    volumes:
      - .:/usr/src
    links:
      - mongodb 
    depends_on:
      - mongodb  
      
    logging:
      driver: "json-file"
      options:
        max-file: "5"   
        max-size: "10m" 
    restart: always  
