
version: '3.8'


services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - 'mongodb:/data/db'

     
  app:
    container_name: encurtadordelink
    build: .  
    command: npm start
    env_file:
      - .env
    ports:
      - "3333:3333"
    
    volumes:
      - .:/usr/src
    links:
      - mongo
    depends_on:
      - mongo 
      
    logging:
      driver: "json-file"
      options:
        max-file: "5"   
        max-size: "10m" 
    restart: always  

volumes:
    mongodb:
      driver: local 